# Generated by Django 3.1.6 on 2021-04-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stenography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.TextField(max_length=15)),
                ('uploaded_image', models.ImageField(upload_to='up_pictures')),
                ('msg_to_encode', models.TextField(max_length=250)),
                ('session_key', models.TextField(unique=True)),
                ('uploaded_on_date', models.DateField(auto_now_add=True)),
                ('uploaded_on_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
